export default interface User {
    avatar_url: string,
    bio: string,
    username: string,
    usernameWin: boolean,
    name: string,
    nameWin: boolean,
    location: string,
    locationWin: boolean,
    titles: string[],
    titlesWin: boolean,
    ["favorite-language"]: string,
    favLangWin: boolean,
    ["total-stars"]: number,
    totalStarsWin: boolean,
    ["highest-starred"]: number,
    highestStarWin: boolean,
    ["public-repos"]: number,
    publicReposWin: boolean,
    ["perfect-repos"]: number,
    perfectReposWin: boolean,
    followers: number,
    followersWin: boolean,
    following: number,
    followingWin: boolean,
    points: number,
    winner: boolean
}